### ISSUE TITLE
importing xcolor produces an error

### ISSUE THREAD

**Issue by houssam-e** [tiarno/plastex#19]
This minimal example:

    \documentclass{article}

    \usepackage{xcolor}

    \begin{document}
        Hello world.
    \end{document}

Produces an error:

        File "/home/h2sm/projects/dev/plastex/plasTeX/TeX.py", line 1620, in readInteger
            log.warning('Missing number%s, treating as `0`. (%s)', self.lineInfo, t)
    UnboundLocalError: local variable 't' referenced before assignment

I'm using the latest github version

**Comment by tiarno** [comment]
Not all LaTeX packages are supported and xcolor is one that is not. You can see how to add a package in the documentation: http://tiarno.github.io/plastex/
particularly, this little article: http://tiarno.github.io/plastex/tutorials/

However, the `color` package is supported, so that might work for you.
