### ISSUE TITLE
Trouble at starting plastex: StopIteration

### ISSUE THREAD

**Issue by JVAQUEROM** [tiarno/plastex#44]
Hello, I am a newbie to plastex. I ran the "python setup.py install" to install plastex and when in run plastex i get this error:

`plasTeX version 1.0
Traceback (most recent call last):
  File "/usr/bin/plastex", line 128, in <module>
    main(sys.argv)
  File "/usr/bin/plastex", line 31, in main
    collect_renderer_config(config)
  File "/usr/bin/plastex", line 18, in collect_renderer_config
    renderers = next(os.walk(renderers_dir))[1]
StopIteration
`

It does not matter if I select a .tex file or run just "plastex" command. Any tips?

Thank you in advance.

**Comment by PatrickMassot** [comment]
Obviously this should not happen. Unfortunately I'm not an expert in how setup.py install works but clearly there seems to be trouble coming from differences between what happens when the package is installed system wide vs in user space. The way ``collect_renderer_config`` figures out where the plasTeX package is actually installed is not robust enough.

Until we find a better solution you can edit ``/usr/bin/plastex`` and comment out line 31, ie change it from
```python
    collect_renderer_config(config)
```
to
```python
    #collect_renderer_config(config)
```

If you are a beginner plasTeX user you won't need this line soon.

**Comment by kesmit13** [comment]
I think I see the problem.  __file__ is used in plastex which is probably in a bin directory when installed.  I think what it should use is plasTeX.__file__.

**Comment by PatrickMassot** [comment]
That sounds promising. @JVAQUEROM could you uncomment line 31 and instead change line 16 to
```python
    plastex_dir = os.path.dirname(os.path.realpath(plasTeX.__file__))
```
(beware if you are not a python programmer, the fact this line starts with four spaces is crucial) and report here?

**Comment by kesmit13** [comment]
After running a few checks, this seems to fix the problem.

**Comment by JVAQUEROM** [comment]
Thank you!! I just tried and the modification on line 16 did the trick.

Congratulations for such a great software!!
