### ISSUE TITLE
Incorrect ids

### ISSUE THREAD

**Issue by kskyten** [tiarno/plastex#50]
I'm trying to implement cross referencing for a [MathBook XML](https://mathbook.pugetsound.edu/) renderer.
I need to add a valid xml:id attribute to each node that is to be referenced and a corresponding label in the referencing node. I'm using the [source code](http://math.dartmouth.edu/~prob/prob/prob.tar.gz) from [this book](http://www.dartmouth.edu/%7Echance/teaching%5Faids/books%5Farticles/probability%5Fbook/book.html) to test the conversion. Using `node.id` seems to get the correct label only sometimes. For example In the first chapter the id for the first section is for some reason `exam 1.05` instead of `sec 1.1` like it should be.
Converting
```
\chapter{Discrete Probability Distributions} \label{chp 1}
\setcounter{page}{1}

\section{Simulation of Discrete Probabilities} \label{sec 1.1}

\subsection*{Probability}
In this chapter, we shall first consider chance experiments with a finite number of
...
```
results in
```
<chapter xml:id="chp 1"> 
  <title>Discrete Probability Distributions</title> 
  <p> 
  </p>
  <section xml:id="exam 1.05">
    <title>Simulation of Discrete Probabilities</title> 
    <p>
    </p>
    <subsection xml:id="a0000000004"> 
      <title>Probability</title>
In this chapter, we shall first consider chance experiments with a finite number of
...
```
How do I label the sections correctly or at least improve the accuracy?

**Comment by PatrickMassot** [comment]
This is a weird bug. @kesmit13 the id ``exam 1.05`` does appear in a ``\label`` in the same file but inside an ``example`` environment.

I think the source of the problem lies before what you are showing. Here I cannot have plasTeX compiling your ``prob.tex`` because it chokes on ``usepackage{theorem}``. Since the ``example`` env is created by theorem, there is no hope here. How do you get to see this id issue?

On my side I can do:
```python
from plasTeX import TeX
t = TeX.TeX(file='ch1.tex')
doc=t.parse()
doc.getElementsByTagName('section')[0].id
```
to see the incorrect id but, in the mean time, the parse method complains about unknown command ``example``.

So I would say you need to explain how you worked around the theorem package issue. And again, see discussion in #46.

**Comment by kskyten** [comment]
I just commented the theorem package out in the latex source and used the default xml renderer example from the documentation as a basis for my renderer. I currently have the following macros defined.
```
[Command]
emx = self
putfig = arg1 arg2 arg3
exercises = 
proof = 

[Environment]
theorem = ( title:str )
corollary = ( title:str )
exercise = 
example = ( title:str )
definition = ( title:str )
```

**Comment by kskyten** [comment]
There was also a problem with parsing the backmatter in the file `back.tex` so I commented that out as well. I'm mostly just concerned with the logical markup of the tex files as I want a bare bones XML version and let MathBook handle the formatting.

**Comment by kesmit13** [comment]
This is actually working as designed although it does look a bit strange here.  Labels in plasTeX don't work anything like they do in LaTeX.  LaTeX just puts an anchor in at the point of the label so it knows what page it is on.  plasTeX has to do more.  It has to associate a label with a particular node.  It does this by applying labels to the last "label-able" node.  In this case, the last label-able node is the section because it doesn't know that the example environment can take labels.  If you set an attribute called labelable to True on the example environment, it should fix your problem.

**Comment by PatrickMassot** [comment]
Yes, this is why I kept referring to #46 (and now #53): the issue lies in the ``example`` environment, not in ``\label``. I will try to find some time to work on this example TeX source though, because I think having a MathBook renderer would be nice. I didn't know this project, it looks nice.
